version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:18.20.4 
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-npm-deps
      - run:
          name: Run Tests with Coverage
          command: npm run test:coverage || echo "Tests failed with exit code $?"
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results
      - coveralls/upload

workflows:
  version: 2
  build-test-coverage:
    jobs:
      - build